In [5]:
## Numpy

import numpy as np

# 1. crear un arreglo

# 1.1 desde listas

vec = np.array([10, 20, 30, 40])
print("Arreglo desde listas: ")
print(vec)
print("\n")

# 1.2 desde matrices

matriz = np.array([[7, 14, 21], [28, 35, 42]])
print("Matriz: ")
print(matriz)
print("\n")

# 1.3 con rangos

rango_valores = np.arange(5, 50, 5)
print("Arreglo con rangos: ")
print(rango_valores)
print("\n")

# 1.4 arreglo con ceros y unos

ceros = np.zeros((2, 5))
unos = np.ones((4, 3))
print("Arreglo de ceros: ")
print(ceros)
print("\n")
print("Arreglo de unos: ")
print(unos)
print("\n")

# 1.5 aleatorios

aleatorio_flotante = np.random.rand(4, 4)
aleatorio_enteros = np.random.randint(50, 150, (3, 4))

print("Arreglo aleatorio: ")
print(aleatorio_flotante)
print("\n")
print("Arreglo aleatorio de enteros: ")
print(aleatorio_enteros)


Arreglo desde listas: 
[10 20 30 40]


Matriz: 
[[ 7 14 21]
 [28 35 42]]


Arreglo con rangos: 
[ 5 10 15 20 25 30 35 40 45]


Arreglo de ceros: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Arreglo de unos: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Arreglo aleatorio: 
[[0.80806177 0.53838468 0.56853772 0.81881911]
 [0.71461228 0.85230266 0.21894038 0.47588476]
 [0.82860814 0.70649109 0.28784366 0.67566496]
 [0.45126887 0.78543362 0.68873416 0.07748675]]


Arreglo aleatorio de enteros: 
[[141 100  64  67]
 [ 83  94 120  89]
 [ 93  89 119  52]]
